### ISSUE TITLE
Fout in SLD's

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/IMGeo#10]
In de volgende SLD's
\visualisatie\2.0\icoonvisualisatie\sld-0107-sensor-lijn.xml
\visualisatie\2.0\plantopovisualisatie\sld-0107-sensor-plan-lijn.xml
\visualisatie\2.0\icoonvisualisatie\sld-0109-waterinrichtingselement-lijn.xml
\visualisatie\2.0\plantopovisualisatie\sld-0109-waterinrichtingselement-plan-lijn.xml
\visualisatie\2.0\icoonvisualisatie\sld-0110-weginrichtingselement-lijn.xml
\visualisatie\2.0\plantopovisualisatie\sld-0110-weginrichtingselement-plan-lijn.xml

Zit een aantal XML fouten: 
Engine name: Xerces
Severity: error
Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/sld":Graphic}'. One of '{"http://www.opengis.net/sld":Halo, "http://www.opengis.net/sld":Fill}' is expected.

**Comment by emacgillavry** [comment]
Deze loop ik door. Er volgt een pull-request.

**Comment by emacgillavry** [comment]
Het gaat bij allemaal om een Graphic in een TextSymbolizer. Dit is foute XML, maar deze "graphics in a textsymbolizer" method was approved as a geotools SLD extension volgens http://osgeo-org.1560.x6.nabble.com/Graphics-not-showing-tp3810340p3810344.html. GeoServer/Geotools kan ermee overweg. Geen aanpassingen voor nu nodig dus.
