### ISSUE TITLE
Onbekend element 'VendorOption' in SLDs

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/IMGeo#11]
In (veel van) de SLD's in \visualisatie\2.0\plantopovisualisatie\ zit het element VendorOption. Dit is voor zover ik weet geen standaard SLD maar een geoserver specifieke toevoeging. 

Levert dit geen problemen op voor andere toepassingen van de SLD? 

Voorbeeld validatiefout:
Engine name: Xerces
Severity: error
Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/sld":VendorOption}'. One of '{"http://www.opengis.net/sld":Rule}' is expected.
Start location: 397:6
End location: 397:18

**Comment by emacgillavry** [comment]
Inderdaad is het element 'VendorOption' specifiek voor GeoServer. In de template is dit op een implementatie-onafhankelijke manier beschreven. De SLD's zijn met name voor de Landelijke Voorziening (in casu PDOK). Daarmee is indertijd afgestemd, dat hun versie van GeoServer deze VendorOption ondersteunt.

**Comment by lvdbrink** [comment]
Dan laten we het voor nu zo. Als mensen hier last van blijken te hebben kijken we hoe dit anders kan.

**Comment by spingerfitz** [comment]
Ik probeer de pastelvisualisatie van BGT te gebruiken in GeoServer 2.9.1 en krijg bij validatie van pastel-wegdeel-vlak.sld een foutmelding voor `<sld:VendorOption name="graphic-margin">10 10 10 10</sld:VendorOption>` in het onderdeel `PolygonSymbolizer`. 
`cvc-complex-type.2.4.a: Invalid content was found starting with element 'sld:VendorOption'. One of '{"http://www.opengis.net/sld":Stroke}' is expected.`
Via Google vind ik [meer mensen met dit probleem](https://osgeo-org.atlassian.net/browse/GEOS-5540). Volgens de [documentatie](http://docs.geoserver.org/stable/en/user/styling/sld/extensions/margins.html) van GeoServer zou VendorOption ook moeten kunnen bij een PolygonSymbolizer, maar in werkelijkheid werkt dit niet.
Als ik het xsd-schema bekijk van de SLD's in GeoServer via `<server>/geoserver/schemas/sld/StyledLayerDescriptor.xsd`, dan is VendorOption volgens mij inderdaad niet toegestaan als onderdeel van PolygonSymbolizer, maar wel voor TextSymbolizer.
Ook bij [nieuwste versie 2.12.1 van GeoServer](https://github.com/geoserver/geoserver/blob/2.12.x/src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd) lijkt VendorOption bij PolygonSymbolizer niet toegestaan.
@emacgillavry : Hoe heb jij dit wel werkend gekregen voor een GeoServer?

**Comment by emacgillavry** [comment]
Dag Jelle Frans,

Wij gebruiken inmiddels GeoServer versie 2.12, waar je dit wel in kunt
gebruiken zoals in het voorbeeld op
http://docs.geoserver.org/stable/en/user/styling/sld/extensions/margins.html
.

Een andere mogelijkheid om dit patroon te implementeren zou een GraphicFill
zijn met een patroon. In de BGT-standaardvisualisatie wordt deze aanpak
toegepast voor BegroeidTerreindeel, bijvoorbeeld bij fysiekVoorkomen met de
waarden "loofbos", "naaldbos" of "gemengd bos".

Ik overleg met Geonovum om dit zo aan te passen voor bredere
compatibiliteit.

Met vriendelijke groeten,

Edward Mac Gillavry

Op 11 dec. 2017 17:52 schreef "Jelle Frans van der Woude" <
notifications@github.com>:

**Comment by spingerfitz** [comment]
Ik heb mijn GeoServer geüpgrade naar 2.12.1, maar dit maakt geen verschil. Ik krijg nog dezelfde foutmelding.
`line 135: cvc-complex-type.2.4.a: Invalid content was found starting with element 'sld:VendorOption'. One of '{"http://www.opengis.net/sld":Stroke}' is expected.`
 Bijgevoegd de StyledLayerDescriptor.xsd van GeoServer 2.12.1. 
[StyledLayerDescriptor.xsd.zip](https://github.com/Geonovum/IMGeo/files/1553710/StyledLayerDescriptor.xsd.zip)
Is die van jou misschien anders?

**Comment by emacgillavry** [comment]
Inderdaad krijgen wij ook dezelfde foutmelding. Wellicht een bug om te melden bij GeoServer, want het werkt wel gewoon en geeft een margin om het symbool heen.

**Comment by emacgillavry** [comment]
Even nagekeken en met PDOK team overlegd. Klopt inderdaad, dat de
foutmelding blijft. Desalniettemin doet de VendorOption precies wat ie moet
doen. Lijkt erop, dat de XSD bijgewerkt moet worden. Iets om even op
GeoServer mailinglijst aan te kaarten. Vandaag of gisteren is versie 2.11.4
uitgekomen.
